# Generated by Django 4.2 on 2025-10-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_event_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='TBA', max_length=255),
        ),
    ]
