# Generated by Django 4.2 on 2025-10-19 06:11

from django.db import migrations, models
import django.utils.timezone
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_achievement_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='date_awarded',
        ),
        migrations.AddField(
            model_name='achievement',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        

        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),

        migrations.AddField(
            model_name='achievement',
            name='date_earned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
