# Generated by Django 4.2 on 2025-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_event_created_by_event_max_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='TBA', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_slots',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
