# Generated by Django 4.2 on 2025-10-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_achievement_date_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
