# Generated by Django 4.2 on 2025-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late')], default='Absent', max_length=20),
        ),
    ]
