# Generated by Django 4.2 on 2025-09-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_actionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_status',
        ),
        migrations.AddField(
            model_name='member',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
