# Generated by Django 4.2 on 2025-09-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_posted_by_announcement_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='target_announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.announcement'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='target_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
    ]
