# Generated by Django 4.2 on 2025-10-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_remove_auditlog_ip_address_alter_auditlog_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='achievement',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
